Revert "engine: fix uadk engine compatibility issue"
This reverts commit ed37fc700d49f4940974d36c6bddf2af5e3d3cb7.
Fix build error:
e_uadk.c:244:12: warning: implicit declaration of function

Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>