uadk_util: fix clang build error
autoreconf -i
./configure CC=clang
make -j8

reports error:
uadk_utils.c:53:33: error: unknown register name 'q0' in asm
uadk_utils.c:53:39: error: unknown register name 'q1' in asm

Fix with "v0", "v1", instead of "q0", "q1"

Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>